language: cpp

sudo: required

dist: bionic

compiler: gcc

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-8 cmake git libusb-1.0-0-dev librtlsdr-dev libasound2-dev libfftw3-dev libfftw3-single3 libpopt-dev

script:
  - make
