name: "C++ CI"

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README**'
      - 'doc/**'
      - 'octave/**'
      - '.github/workflows/codeql-analysis.yaml'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README**'
      - 'doc/**'
      - 'octave/**'
      - '.github/workflows/codeql-analysis.yaml'

jobs:
  build:
    name: Build and install
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-22.04, ubuntu-24.04 ]
    steps:
      - name: Install build requirements
        run: >-
          sudo apt-get update ;
          sudo apt-get install -y
          g++ cmake git libusb-1.0-0-dev librtlsdr-dev libasound2-dev
          libfftw3-dev libfftw3-single3 libpopt-dev libairspy-dev
          libsigc++-2.0-dev zlib1g-dev libuv1-dev libssl-dev

      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure
        run: rm -rf build ; cmake -B build -DCMAKE_INSTALL_PREFIX=/usr

      - name: Build
        run: cd build && make

      - name: Install
        run: cd build && sudo make install

      - name: Uninstall
        run: cd build && sudo make uninstall
